[package]
name = "request_demo"
version = "0.1.0"
authors = ["Aqrun <aqrun@oicnp.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
curl = "0.4"
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
dotenv = "0.10"
serde_derive = "1.0"
lazy_static = "1.0"
